name: Python CI

# Trigger the workflow on any push to the main branch or pull request
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Call composite action from external repo
        uses: Pawankumarmeena425/CompositeAction@test
        with:
          input1: "This is the first input"
          input2: "This is the second input"
